package com.bayside.app.opinion.war.concern.bo;

import java.util.Date;

public class ArticleBo {
   
    private String id;
    private String content;
	private String tittle;

    private String domain;
  


	private Date pubdate;
    private String articleid;
   
    private String dataSource;

    private String url;
    private String author;

    private String keywordRule;

    private Boolean reportinfo;

    private Boolean attention;

    
    private Boolean warning;

    
    private Boolean readsign;

    
    private Boolean briefing;

    private String emotion;

   
    private String contentType;

    
    private String formats;

    
    private Integer readcount;

    
    private Integer commtcount;

    
    private Integer repeatcount;

    
    private Integer aggreecount;

   
    private Integer score;

   
    private Integer similarnum;

   
    private Integer relateWord;

   
    private Integer opinionWord;

    private Integer negativeWord;

   
    private Integer positiveWord;

    private Integer warningWord;

   
    private Integer newsindex;

    
    private Integer searchNum;

    
    private Date updatetime;
    
    private Date kaishitime;
    private Date jieshushijian;
    private String imgUrl;
    private String view_point;
    private String abstrac;
    
    public String getImgUrl() {
		return imgUrl;
	}


	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	 public String getDomain() {
			return domain;
		}


		public void setDomain(String domain) {
			this.domain = domain;
		}
	public String getView_point() {
		return view_point;
	}


	public void setView_point(String view_point) {
		this.view_point = view_point;
	}


	public String getAbstrac() {
		return abstrac;
	}


	public void setAbstrac(String abstrac) {
		this.abstrac = abstrac;
	}


	public String getId() {
        return id;
    }
   
   
    public Date getKaishitime() {
		return kaishitime;
	}


	public void setKaishitime(Date kaishitime) {
		this.kaishitime = kaishitime;
	}


	public Date getJieshushijian() {
		return jieshushijian;
	}


	public void setJieshushijian(Date jieshushijian) {
		this.jieshushijian = jieshushijian;
	}


	public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
    
    public String getArticleid() {
        return articleid;
    }

   
    public void setArticleid(String articleid) {
        this.articleid = articleid == null ? null : articleid.trim();
    }
    
    public String getContent() {
        return content;
    }

   
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
    
    public String getUrl() {
        return url;
    }

   
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
    
    
    
    public String getTittle() {
        return tittle;
    }

   
    public void setTittle(String tittle) {
        this.tittle = tittle == null ? null : tittle.trim();
    }

   
    public Date getPubdate() {
        return pubdate;
    }

   
    public void setPubdate(Date pubdate) {
        this.pubdate = pubdate;
    }

   
    public String getDataSource() {
        return dataSource;
    }

   
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource == null ? null : dataSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_subject_article.author
     *
     * @return the value of bs_subject_article.author
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_subject_article.author
     *
     * @param author the value for bs_subject_article.author
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_subject_article.keyword_rule
     *
     * @return the value of bs_subject_article.keyword_rule
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public String getKeywordRule() {
        return keywordRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_subject_article.keyword_rule
     *
     * @param keywordRule the value for bs_subject_article.keyword_rule
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public void setKeywordRule(String keywordRule) {
        this.keywordRule = keywordRule == null ? null : keywordRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_subject_article.reportinfo
     *
     * @return the value of bs_subject_article.reportinfo
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public Boolean getReportinfo() {
        return reportinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_subject_article.reportinfo
     *
     * @param reportinfo the value for bs_subject_article.reportinfo
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public void setReportinfo(Boolean reportinfo) {
        this.reportinfo = reportinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_subject_article.attention
     *
     * @return the value of bs_subject_article.attention
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public Boolean getAttention() {
        return attention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_subject_article.attention
     *
     * @param attention the value for bs_subject_article.attention
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public void setAttention(Boolean attention) {
        this.attention = attention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_subject_article.warning
     *
     * @return the value of bs_subject_article.warning
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public Boolean getWarning() {
        return warning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_subject_article.warning
     *
     * @param warning the value for bs_subject_article.warning
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public void setWarning(Boolean warning) {
        this.warning = warning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_subject_article.readsign
     *
     * @return the value of bs_subject_article.readsign
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public Boolean getReadsign() {
        return readsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_subject_article.readsign
     *
     * @param readsign the value for bs_subject_article.readsign
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public void setReadsign(Boolean readsign) {
        this.readsign = readsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_subject_article.briefing
     *
     * @return the value of bs_subject_article.briefing
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public Boolean getBriefing() {
        return briefing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_subject_article.briefing
     *
     * @param briefing the value for bs_subject_article.briefing
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public void setBriefing(Boolean briefing) {
        this.briefing = briefing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_subject_article.emotion
     *
     * @return the value of bs_subject_article.emotion
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public String getEmotion() {
        return emotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_subject_article.emotion
     *
     * @param emotion the value for bs_subject_article.emotion
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public void setEmotion(String emotion) {
        this.emotion = emotion == null ? null : emotion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_subject_article.content_type
     *
     * @return the value of bs_subject_article.content_type
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_subject_article.content_type
     *
     * @param contentType the value for bs_subject_article.content_type
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public void setContentType(String contentType) {
        this.contentType = contentType == null ? null : contentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_subject_article.formats
     *
     * @return the value of bs_subject_article.formats
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public String getFormats() {
        return formats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_subject_article.formats
     *
     * @param formats the value for bs_subject_article.formats
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public void setFormats(String formats) {
        this.formats = formats == null ? null : formats.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_subject_article.readcount
     *
     * @return the value of bs_subject_article.readcount
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public Integer getReadcount() {
        return readcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_subject_article.readcount
     *
     * @param readcount the value for bs_subject_article.readcount
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public void setReadcount(Integer readcount) {
        this.readcount = readcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_subject_article.commtcount
     *
     * @return the value of bs_subject_article.commtcount
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public Integer getCommtcount() {
        return commtcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_subject_article.commtcount
     *
     * @param commtcount the value for bs_subject_article.commtcount
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public void setCommtcount(Integer commtcount) {
        this.commtcount = commtcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_subject_article.repeatcount
     *
     * @return the value of bs_subject_article.repeatcount
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public Integer getRepeatcount() {
        return repeatcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_subject_article.repeatcount
     *
     * @param repeatcount the value for bs_subject_article.repeatcount
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public void setRepeatcount(Integer repeatcount) {
        this.repeatcount = repeatcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_subject_article.aggreecount
     *
     * @return the value of bs_subject_article.aggreecount
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public Integer getAggreecount() {
        return aggreecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_subject_article.aggreecount
     *
     * @param aggreecount the value for bs_subject_article.aggreecount
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public void setAggreecount(Integer aggreecount) {
        this.aggreecount = aggreecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_subject_article.score
     *
     * @return the value of bs_subject_article.score
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_subject_article.score
     *
     * @param score the value for bs_subject_article.score
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_subject_article.similarnum
     *
     * @return the value of bs_subject_article.similarnum
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public Integer getSimilarnum() {
        return similarnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_subject_article.similarnum
     *
     * @param similarnum the value for bs_subject_article.similarnum
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public void setSimilarnum(Integer similarnum) {
        this.similarnum = similarnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_subject_article.relate_word
     *
     * @return the value of bs_subject_article.relate_word
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public Integer getRelateWord() {
        return relateWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_subject_article.relate_word
     *
     * @param relateWord the value for bs_subject_article.relate_word
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public void setRelateWord(Integer relateWord) {
        this.relateWord = relateWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_subject_article.opinion_word
     *
     * @return the value of bs_subject_article.opinion_word
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public Integer getOpinionWord() {
        return opinionWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_subject_article.opinion_word
     *
     * @param opinionWord the value for bs_subject_article.opinion_word
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public void setOpinionWord(Integer opinionWord) {
        this.opinionWord = opinionWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_subject_article.negative_word
     *
     * @return the value of bs_subject_article.negative_word
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public Integer getNegativeWord() {
        return negativeWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_subject_article.negative_word
     *
     * @param negativeWord the value for bs_subject_article.negative_word
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public void setNegativeWord(Integer negativeWord) {
        this.negativeWord = negativeWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_subject_article.positive_word
     *
     * @return the value of bs_subject_article.positive_word
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public Integer getPositiveWord() {
        return positiveWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_subject_article.positive_word
     *
     * @param positiveWord the value for bs_subject_article.positive_word
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public void setPositiveWord(Integer positiveWord) {
        this.positiveWord = positiveWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_subject_article.warning_word
     *
     * @return the value of bs_subject_article.warning_word
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public Integer getWarningWord() {
        return warningWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_subject_article.warning_word
     *
     * @param warningWord the value for bs_subject_article.warning_word
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public void setWarningWord(Integer warningWord) {
        this.warningWord = warningWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_subject_article.newsindex
     *
     * @return the value of bs_subject_article.newsindex
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public Integer getNewsindex() {
        return newsindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_subject_article.newsindex
     *
     * @param newsindex the value for bs_subject_article.newsindex
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public void setNewsindex(Integer newsindex) {
        this.newsindex = newsindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_subject_article.search_num
     *
     * @return the value of bs_subject_article.search_num
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public Integer getSearchNum() {
        return searchNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_subject_article.search_num
     *
     * @param searchNum the value for bs_subject_article.search_num
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public void setSearchNum(Integer searchNum) {
        this.searchNum = searchNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_subject_article.updatetime
     *
     * @return the value of bs_subject_article.updatetime
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_subject_article.updatetime
     *
     * @param updatetime the value for bs_subject_article.updatetime
     *
     * @mbggenerated Tue Jul 26 14:33:07 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
    public ArticleBo() {
		// TODO Auto-generated constructor stub
	}


	public ArticleBo(String id, String content, String tittle, Date pubdate, String articleid, String dataSource,
			String url, String author, String keywordRule, Boolean reportinfo, Boolean attention, Boolean warning,
			Boolean readsign, Boolean briefing, String emotion, String contentType, String formats, Integer readcount,
			Integer commtcount, Integer repeatcount, Integer aggreecount, Integer score, Integer similarnum,
			Integer relateWord, Integer opinionWord, Integer negativeWord, Integer positiveWord, Integer warningWord,
			Integer newsindex, Integer searchNum, Date updatetime, Date kaishitime, Date jieshushijian) {
		this.id = id;
		this.content = content;
		this.tittle = tittle;
		this.pubdate = pubdate;
		this.articleid = articleid;
		this.dataSource = dataSource;
		this.url = url;
		this.author = author;
		this.keywordRule = keywordRule;
		this.reportinfo = reportinfo;
		this.attention = attention;
		this.warning = warning;
		this.readsign = readsign;
		this.briefing = briefing;
		this.emotion = emotion;
		this.contentType = contentType;
		this.formats = formats;
		this.readcount = readcount;
		this.commtcount = commtcount;
		this.repeatcount = repeatcount;
		this.aggreecount = aggreecount;
		this.score = score;
		this.similarnum = similarnum;
		this.relateWord = relateWord;
		this.opinionWord = opinionWord;
		this.negativeWord = negativeWord;
		this.positiveWord = positiveWord;
		this.warningWord = warningWord;
		this.newsindex = newsindex;
		this.searchNum = searchNum;
		this.updatetime = updatetime;
		this.kaishitime = kaishitime;
		this.jieshushijian = jieshushijian;
	}


    
}